"""Add model evaluations

Revision ID: 4d68d979374c
Revises: 2026_06_23_142811
Create Date: 2026-06-23 10:54:10.526952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d68d979374c'
down_revision: Union[str, Sequence[str], None] = '2026_06_23_142811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_evaluations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('overall_accuracy', sa.Float(), nullable=True),
    sa.Column('winner_prediction_accuracy', sa.Float(), nullable=True),
    sa.Column('scoreline_accuracy', sa.Float(), nullable=True),
    sa.Column('probability_accuracy', sa.Float(), nullable=True),
    sa.Column('player_prediction_accuracy', sa.Float(), nullable=True),
    sa.Column('matches_tested', sa.Integer(), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('final_ai_score', sa.Float(), nullable=True),
    sa.Column('strength_category', sa.String(length=255), nullable=True),
    sa.Column('weakness_category', sa.String(length=255), nullable=True),
    sa.Column('evaluation_notes', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model_submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('model_submissions', sa.Column('model_name', sa.String(length=255), nullable=True))
    op.add_column('model_submissions', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('model_submissions', sa.Column('model_type', sa.String(length=255), nullable=True))
    op.add_column('model_submissions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('model_submissions', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('model_submissions', sa.Column('status', sa.Enum('UPLOADED', 'TESTING', 'EVALUATED', 'FAILED', name='model_status_enum', create_constraint=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('model_submissions', 'status')
    op.drop_column('model_submissions', 'notes')
    op.drop_column('model_submissions', 'description')
    op.drop_column('model_submissions', 'model_type')
    op.drop_column('model_submissions', 'version')
    op.drop_column('model_submissions', 'model_name')
    op.drop_table('model_evaluations')
    # ### end Alembic commands ###
