"""initial schema

Revision ID: 58877d976e6e
Revises: 
Create Date: 2026-06-10 10:54:54.721867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58877d976e6e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('match_number', sa.Integer(), nullable=False),
    sa.Column('home_team_name', sa.String(length=255), nullable=False),
    sa.Column('away_team_name', sa.String(length=255), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('freeze_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'FROZEN', 'COMPLETED', 'RESULT_ENTERED', 'SCORED', name='match_status', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('actual_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('actual_winner', sa.Enum('HOME', 'AWAY', 'DRAW', name='winner_enum', create_constraint=True), nullable=False),
    sa.Column('actual_home_goals', sa.Integer(), nullable=True),
    sa.Column('actual_away_goals', sa.Integer(), nullable=True),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_index('ix_actual_results_match_id', 'actual_results', ['match_id'], unique=True)
    op.create_table('cumulative_phase_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('total_earned_points', sa.Float(), nullable=True),
    sa.Column('matches_played', sa.Integer(), nullable=True),
    sa.Column('phase1_score', sa.Float(), nullable=True),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('presentation_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_index('ix_cumulative_phase_scores_team_id', 'cumulative_phase_scores', ['team_id'], unique=True)
    op.create_table('leaderboard',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('phase1_score', sa.Float(), nullable=True),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('presentation_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_index('ix_leaderboard_rank', 'leaderboard', ['rank'], unique=False)
    op.create_index('ix_leaderboard_team_id', 'leaderboard', ['team_id'], unique=True)
    op.create_table('predictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.String(length=255), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING_VALIDATION', 'VALIDATED', 'INVALID', 'LATE', name='prediction_status', create_constraint=True), nullable=False),
    sa.Column('predicted_winner', sa.Enum('HOME', 'AWAY', 'DRAW', name='winner_enum', create_constraint=True), nullable=False),
    sa.Column('home_win_probability', sa.Float(), nullable=True),
    sa.Column('draw_probability', sa.Float(), nullable=True),
    sa.Column('away_win_probability', sa.Float(), nullable=True),
    sa.Column('predicted_home_goals', sa.Integer(), nullable=True),
    sa.Column('predicted_away_goals', sa.Integer(), nullable=True),
    sa.Column('home_clean_sheet_probability', sa.Float(), nullable=True),
    sa.Column('away_clean_sheet_probability', sa.Float(), nullable=True),
    sa.Column('first_goal_team', sa.Enum('HOME', 'AWAY', 'NONE', name='first_goal_team_enum', create_constraint=True), nullable=True),
    sa.Column('both_teams_to_score_probability', sa.Float(), nullable=True),
    sa.Column('total_goals_prediction', sa.Integer(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_predictions_match_id', 'predictions', ['match_id'], unique=False)
    op.create_index('ix_predictions_team_id', 'predictions', ['team_id'], unique=False)
    op.create_index('ix_predictions_team_match', 'predictions', ['team_id', 'match_id'], unique=True)
    op.create_table('presentation_evaluations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('ai_explanation_score', sa.Integer(), nullable=True),
    sa.Column('qa_score', sa.Integer(), nullable=True),
    sa.Column('delivery_score', sa.Integer(), nullable=True),
    sa.Column('raw_total', sa.Integer(), nullable=True),
    sa.Column('presentation_score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Enum('A', 'B', 'C', name='grade_enum', create_constraint=True), nullable=True),
    sa.Column('multiplier', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_index('ix_presentation_evaluations_team_id', 'presentation_evaluations', ['team_id'], unique=True)
    op.create_table('scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('winner_points', sa.Integer(), nullable=True),
    sa.Column('scoreline_points', sa.Integer(), nullable=True),
    sa.Column('probability_points', sa.Integer(), nullable=True),
    sa.Column('player_points', sa.Integer(), nullable=True),
    sa.Column('base_score', sa.Float(), nullable=True),
    sa.Column('match_rank', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Enum('A', 'B', 'C', name='grade_enum', create_constraint=True), nullable=True),
    sa.Column('multiplier', sa.Integer(), nullable=True),
    sa.Column('earned_points', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scores_match_id', 'scores', ['match_id'], unique=False)
    op.create_index('ix_scores_team_match', 'scores', ['team_id', 'match_id'], unique=True)
    op.create_table('technical_evaluations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('code_quality', sa.Integer(), nullable=True),
    sa.Column('backend_quality', sa.Integer(), nullable=True),
    sa.Column('teamwork', sa.Integer(), nullable=True),
    sa.Column('ai_explanation', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_index('ix_technical_evaluations_team_id', 'technical_evaluations', ['team_id'], unique=True)
    op.create_table('player_actuals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actual_result_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.String(length=255), nullable=False),
    sa.Column('player_name', sa.String(length=255), nullable=False),
    sa.Column('actual_goals', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actual_result_id'], ['actual_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_player_actuals_actual_result_id', 'player_actuals', ['actual_result_id'], unique=False)
    op.create_table('player_predictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prediction_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.String(length=255), nullable=False),
    sa.Column('player_name', sa.String(length=255), nullable=False),
    sa.Column('goal_probability', sa.Float(), nullable=True),
    sa.Column('predicted_goals', sa.Integer(), nullable=True),
    sa.Column('assist_probability', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_player_predictions_prediction_id', 'player_predictions', ['prediction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_player_predictions_prediction_id', table_name='player_predictions')
    op.drop_table('player_predictions')
    op.drop_index('ix_player_actuals_actual_result_id', table_name='player_actuals')
    op.drop_table('player_actuals')
    op.drop_index('ix_technical_evaluations_team_id', table_name='technical_evaluations')
    op.drop_table('technical_evaluations')
    op.drop_index('ix_scores_team_match', table_name='scores')
    op.drop_index('ix_scores_match_id', table_name='scores')
    op.drop_table('scores')
    op.drop_index('ix_presentation_evaluations_team_id', table_name='presentation_evaluations')
    op.drop_table('presentation_evaluations')
    op.drop_index('ix_predictions_team_match', table_name='predictions')
    op.drop_index('ix_predictions_team_id', table_name='predictions')
    op.drop_index('ix_predictions_match_id', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_leaderboard_team_id', table_name='leaderboard')
    op.drop_index('ix_leaderboard_rank', table_name='leaderboard')
    op.drop_table('leaderboard')
    op.drop_index('ix_cumulative_phase_scores_team_id', table_name='cumulative_phase_scores')
    op.drop_table('cumulative_phase_scores')
    op.drop_index('ix_actual_results_match_id', table_name='actual_results')
    op.drop_table('actual_results')
    op.drop_table('teams')
    op.drop_table('matches')
    # ### end Alembic commands ###
