"""Add judge and leaderboard flags

Revision ID: 6e40fd0a1a21
Revises: 4d68d979374c
Create Date: 2026-06-23 11:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e40fd0a1a21'
down_revision: Union[str, Sequence[str], None] = '4d68d979374c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaderboard_visibility', sa.Column('show_judge_analytics', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('leaderboard_visibility', sa.Column('show_leaderboard_analytics', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leaderboard_visibility', 'show_leaderboard_analytics')
    op.drop_column('leaderboard_visibility', 'show_judge_analytics')
    # ### end Alembic commands ###
